In [1]:
import os
import pathlib
import pandas as pd
import numpy as np
import sys
sys.path.append(str(pathlib.Path(os.getcwd()).parent))

In [8]:
from run.raw_data_query import raw_data_query

In [9]:
help(raw_data_query)

Help on function check_data_exist in module run.metadata_setup.check_data_exist:

check_data_exist(project_id, start_time, end_time, update_metadata=False)
    Check the data existance for a given project.
    Description:
        - This function checks the data existance for the given project and time period.
        - The data existance is checked based on the point list and the raw data.
        - The result is saved as a csv file in the data/project_id folder.


    Args:
        project_id (str): The ID of the project. #'lotte_mart' or 'hdc'
        start_time (str): The start time in local or UTC timezone, formatted as %Y-%m-%d %H:%M:%S%z (e.g., '2024-03-07 00:00:00+0900' or '2024-03-07 00:00:00+0000')
        end_time (str): The end time in local or UTC timezone, formatted as %Y-%m-%d %H:%M:%S%z (e.g., '2024-03-07 00:00:00+0900' or '2024-03-07 00:00:00+0000')
        update_metadata (bool, optional): Whether to update the metadata. Defaults to False.


    Returns:
        None

In [4]:
project_id="lotte_mart"

start_time='2024-03-22 00:00:00+0900' # start_time of data check period (if exist)
end_time='2024-03-23 00:00:00+0900' # end_time of data check period (if exist)

save_data=True # whether to save the data. If True, the data is saved in the save_dir.
save_dir=None # where to save the data. If None, the default directory is used.

# only quries (required==True) and (available=True) of data/{project_id}/{sheet_name}.csv
raw_df=raw_data_query(project_id, start_time, end_time, save_dir=save_dir,save_data=save_data)

default save_dir is download/rawdata/hdc
data is stored in download/rawdata/hdc/raw_data_2024-03-22_2024-03-23.csv

In [5]:
raw_df

,timestamp_local,check_sf_status_ahu11,check_sf_status1_ahu11,i_ahu_elecheat_ahu11,T_ahu_oa_ahu11,T_ahu_ma_ahu11,check_T_ahu_dfsp_ahu11,T_ahu_sa_ahu11,T_ahu_ra_ahu11,check_sf_time_ahu11,...,i_ahu_damper_ahu9,T_ahu_sp_ahu9,T_ahu_oa1_ahu9,RH_ahu_oa1_ahu9,V_ahu_hcw_ahu9,Q_ahu_hcw_ahu9,v_ahu_hcw_ahu9,cum_ahu_hcw_ahu9,T_ahu_hcws_ahu9,T_ahu_hcwr_ahu9
0,2024-03-22 00:00:00+09:00,0.0,0.0,0.0,10.7,24.6,5.0,25.2,25.6,0.0,...,0.0,23.0,9.0,40.0,0.0,0.0,0.0,6029957.0,27.9862,22.2826
1,2024-03-22 00:00:30+09:00,0.0,0.0,0.0,10.7,24.6,5.0,25.2,25.6,0.0,...,0.0,23.0,9.0,39.0,0.0,0.0,0.0,6029957.0,27.9880,22.2881
2,2024-03-22 00:01:00+09:00,0.0,0.0,0.0,10.7,24.6,5.0,25.2,25.6,0.0,...,0.0,23.0,9.0,39.0,0.0,0.0,0.0,6029957.0,28.0194,22.3041
3,2024-03-22 00:01:30+09:00,0.0,0.0,0.0,10.7,24.6,5.0,25.2,25.6,0.0,...,0.0,23.0,9.0,40.0,0.0,0.0,0.0,6029957.0,27.9655,22.2953
4,2024-03-22 00:02:00+09:00,0.0,0.0,0.0,10.7,24.6,5.0,25.2,25.6,0.0,...,0.0,23.0,9.0,40.0,0.0,0.0,0.0,6029957.0,27.9922,22.3061
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2876,2024-03-22 23:58:00+09:00,0.0,0.0,0.0,10.7,22.3,5.0,23.3,25.1,0.0,...,0.0,23.0,14.0,74.0,0.0,0.0,0.0,6030841.0,24.7533,21.3261
2877,2024-03-22 23:58:30+09:00,0.0,0.0,0.0,10.7,22.3,5.0,23.3,25.1,0.0,...,0.0,23.0,14.0,74.0,0.0,0.0,0.0,6030841.0,24.7654,21.3173
2878,2024-03-22 23:59:00+09:00,0.0,0.0,0.0,10.7,22.3,5.0,23.3,25.2,0.0,...,0.0,23.0,14.0,74.0,0.0,0.0,0.0,6030841.0,24.7467,21.3356
2879,2024-03-22 23:59:30+09:00,0.0,0.0,0.0,10.7,22.4,5.0,23.4,25.2,0.0,...,0.0,23.0,14.0,74.0,0.0,0.0,0.0,6030841.0,24.7737,21.3505
2880,2024-03-23 00:00:00+09:00,0.0,0.0,0.0,10.7,22.4,5.0,23.4,25.2,0.0,...,0.0,23.0,14.0,75.0,0.0,0.0,0.0,6030841.0,24.7727,21.3329